In [39]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import spacy

In [40]:
# !python -m spacy download en_core_web_md

In [41]:
sentences = ["President Obama visited Beijing last week", "The first African-American US President arrived at Peking a few days ago",
             "Hamilton beats Button and wins the game", "Button beats Hamilton and wins the game"]

In [42]:
def Jaccard(text1, text2, prints):
  intersection = set(text1.split()) & set(text2.split())
  union = len(set(text1.split()) | set(text2.split()))
  if prints:
    print(set(text1.split()))
    print(set(text2.split()))
    print("overlap: ", intersection)
    print("Total words: ", union)
  return(len(intersection)/union)

In [43]:
Jaccard(sentences[0], sentences[1], True)

{'Obama', 'visited', 'President', 'week', 'Beijing', 'last'}
{'days', 'African-American', 'few', 'first', 'at', 'a', 'ago', 'US', 'The', 'arrived', 'Peking', 'President'}
overlap:  {'President'}
Total words:  17


0.058823529411764705

In [44]:
Jaccard(sentences[2], sentences[3], True)

{'Button', 'beats', 'game', 'and', 'the', 'Hamilton', 'wins'}
{'Button', 'beats', 'game', 'and', 'the', 'Hamilton', 'wins'}
overlap:  {'Button', 'beats', 'game', 'and', 'the', 'Hamilton', 'wins'}
Total words:  7


1.0

In [45]:
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(sentences)

In [47]:
tfidf_matrix.todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.42176478, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.42176478,
         0.42176478, 0.        , 0.3325242 , 0.        , 0.        ,
         0.42176478, 0.42176478, 0.        ],
        [0.30111464, 0.30111464, 0.30111464, 0.        , 0.30111464,
         0.30111464, 0.        , 0.        , 0.        , 0.30111464,
         0.30111464, 0.30111464, 0.        , 0.        , 0.        ,
         0.        , 0.30111464, 0.23740224, 0.19219757, 0.30111464,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.38762515, 0.        ,
         0.        , 0.38762515, 0.        , 0.38762515, 0.        ,
         0.        , 0.        , 0.38762515, 0.38762515, 0.        ,
         0.        , 0.        , 0.        , 0.31381597, 0.        ,
         0.        , 0.        , 0.38762515],
        [0.        , 0.        , 0

# New section

In [48]:
cosine_similarity(tfidf_matrix[0], tfidf_matrix[1])

array([[0.07894199]])

In [49]:
cosine_similarity(tfidf_matrix[2], tfidf_matrix[3])

array([[1.]])

In [35]:
# Load the model with word embeddings
nlp = spacy.load('en_core_web_md')

In [37]:
nlp(sentences[0]).similarity(nlp(sentences[1]))

0.6559949871590907

In [38]:
nlp(sentences[2]).similarity(nlp(sentences[3]))

0.9999999729939644